/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PintuIndexRouteImport } from './routes/pintu.index'
import { Route as Pintu1RouteImport } from './routes/pintu.1'
import { Route as Pintu2RouteImport } from './routes/pintu.2'
import { Route as Pintu3RouteImport } from './routes/pintu.3'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PintuIndexRoute = PintuIndexRouteImport.update({
  id: '/pintu/',
  path: '/pintu/',
  getParentRoute: () => rootRouteImport,
} as any)
const Pintu1Route = Pintu1RouteImport.update({
  id: '/pintu/1',
  path: '/pintu/1',
  getParentRoute: () => rootRouteImport,
} as any)
const Pintu2Route = Pintu2RouteImport.update({
  id: '/pintu/2',
  path: '/pintu/2',
  getParentRoute: () => rootRouteImport,
} as any)
const Pintu3Route = Pintu3RouteImport.update({
  id: '/pintu/3',
  path: '/pintu/3',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/pintu/1': typeof Pintu1Route
  '/pintu/2': typeof Pintu2Route
  '/pintu/3': typeof Pintu3Route
  '/pintu/': typeof PintuIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/pintu/1': typeof Pintu1Route
  '/pintu/2': typeof Pintu2Route
  '/pintu/3': typeof Pintu3Route
  '/pintu': typeof PintuIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/pintu/1': typeof Pintu1Route
  '/pintu/2': typeof Pintu2Route
  '/pintu/3': typeof Pintu3Route
  '/pintu/': typeof PintuIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/pintu/1' | '/pintu/2' | '/pintu/3' | '/pintu/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/pintu/1' | '/pintu/2' | '/pintu/3' | '/pintu'
  id: '__root__' | '/' | '/pintu/1' | '/pintu/2' | '/pintu/3' | '/pintu/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  Pintu1Route: typeof Pintu1Route
  Pintu2Route: typeof Pintu2Route
  Pintu3Route: typeof Pintu3Route
  PintuIndexRoute: typeof PintuIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pintu/': {
      id: '/pintu/'
      path: '/pintu'
      fullPath: '/pintu/'
      preLoaderRoute: typeof PintuIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pintu/1': {
      id: '/pintu/1'
      path: '/pintu/1'
      fullPath: '/pintu/1'
      preLoaderRoute: typeof Pintu1RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pintu/2': {
      id: '/pintu/2'
      path: '/pintu/2'
      fullPath: '/pintu/2'
      preLoaderRoute: typeof Pintu2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pintu/3': {
      id: '/pintu/3'
      path: '/pintu/3'
      fullPath: '/pintu/3'
      preLoaderRoute: typeof Pintu3RouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  Pintu1Route: Pintu1Route,
  Pintu2Route: Pintu2Route,
  Pintu3Route: Pintu3Route,
  PintuIndexRoute: PintuIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
